# Generated by Django 3.1.2 on 2020-10-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dateOfCreate', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('houseNumber', models.CharField(max_length=50)),
                ('flatNumber', models.IntegerField(max_length=50)),
            ],
        ),
    ]
