# Generated by Django 3.1.2 on 2020-10-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0004_auto_20201027_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='dateOfCreate',
        ),
    ]
